# Generated by Django 3.2.6 on 2021-08-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descrtption',
            new_name='description',
        ),
    ]
